apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ci-pipeline-task
spec:
  params:
    - name: repo-url
      type: string
      description: The URL of the Git repository to clone
  workspaces:
    - name: source
      description: The workspace where the Git repository will be cloned
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        git clone $(params.repo-url) $(workspaces.source.path)

    - name: install-dependencies
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

    - name: run-tests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        # Delete any existing contents of the directory if it exists.
        #
        # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"
        # or the root of a mounted volume.
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          # Delete non-hidden files and directories
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
