name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_job:
    runs-on: ubuntu-latest
    
    container:
      image: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true  # Nie blokuje pipeline'a na błędach lintingu, ale je raportuje

      - name: Run unit tests with nose
        run: |
          pip install nose  # Upewnienie się, że nose jest zainstalowane
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
